sudo: required
services:
  - docker

before_install:
  - docker build -t eagerstudent/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true eagerstudent/react-test npm test

after_success:
  - docker build -t eagerstudent/multi-client ./client
  - docker build -t eagerstudent/multi-nginx ./nginx
  - docker build -t eagerstudent/multi-server ./server 
  - docker build -t eagerstudent/multi-worker ./worker
  # Log in to the docker CLI
  -  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push eagerstudent/multi-client
  - docker push eagerstudent/multi-nginx
  - docker push eagerstudent/multi-server
  - docker push eagerstudent/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-dcoker
  env: MultiDcoker-env
  bucket_name: elasticbeanstalk-eu-central-1-554495121728
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
